import type { Metadata } from "next"
import { Navbar } from "@/components/layout/navbar/Navbar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {

    return (
        <div>
            <Navbar className="top-0" />
            <div className=" pt-24 px-4 dark:bg-slate-950 text-slate-800 dark:text-slate-200">
                {children}
            </div>
        </div>
    )
}
