import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark:bg-slate-950 text-slate-950 dark:text-slate-200")}>
        <NextTopLoader />
        <Toaster />
        {children}
      </body>
    </html>
  )
}
