import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter'
})

// import { Roboto_Serif } from "next/font/google";

// export const roboto_serif = Roboto_Serif({
//     weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
//     subsets: ['latin'],
//     style: ['normal', 'italic']
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark:bg-slate-950 text-slate-950 dark:text-slate-200")}>
        <NextTopLoader />
        <Toaster />
        {children}
      </body>
    </html>
  )
}
